const Jimp = require('jimp');
const potrace = require('potrace');
const svgo = require('svgo');
const { generateSkeletonData } = require('../../tools/skeletonizer');

class ShapeGeneratorService {
  #appManager;

  constructor(appManager) {
    this.#appManager = appManager;
  }

  async generateImageFromPrompt({ prompt, provider, apiKey }) {
    try {
      if (!apiKey) {
        return { success: false, error: 'API key is required.', code: 'ERR_NO_API_KEY' };
      }

      if (provider === 'gemini') {
        const url = `https://generativelanguage.googleapis.com/v1beta/models/imagen-3.0-generate-002:generateImages?key=${apiKey}`;
        const response = await fetch(url, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            prompt: prompt,
            numberOfImages: 1,
            outputMimeType: 'image/png',
            aspectRatio: '1:1'
          })
        });

        if (!response.ok) {
          const errText = await response.text();
          let errJson;
          try { errJson = JSON.parse(errText); } catch(e) {}
          const errMsg = errJson?.error?.message || errText || `HTTP ${response.status}`;
          return { success: false, error: `Gemini API Error: ${errMsg}`, code: 'ERR_GEMINI_API' };
        }

        const resData = await response.json();
        if (resData.generatedImages && resData.generatedImages[0]?.image?.imageBytes) {
          return { success: true, base64Data: resData.generatedImages[0].image.imageBytes };
        } else {
          return { success: false, error: 'No image returned in Gemini response.', code: 'ERR_NO_IMAGE' };
        }
      } else if (provider === 'openai') {
        const url = 'https://api.openai.com/v1/images/generations';
        const response = await fetch(url, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${apiKey}`
          },
          body: JSON.stringify({
            model: 'dall-e-3',
            prompt: prompt,
            n: 1,
            size: '1024x1024',
            response_format: 'b64_json'
          })
        });

        if (!response.ok) {
          const errText = await response.text();
          let errJson;
          try { errJson = JSON.parse(errText); } catch(e) {}
          const errMsg = errJson?.error?.message || errText || `HTTP ${response.status}`;
          return { success: false, error: `OpenAI API Error: ${errMsg}`, code: 'ERR_OPENAI_API' };
        }

        const resData = await response.json();
        if (resData.data && resData.data[0]?.b64_json) {
          return { success: true, base64Data: resData.data[0].b64_json };
        } else {
          return { success: false, error: 'No image returned in OpenAI response.', code: 'ERR_NO_IMAGE' };
        }
      } else {
        return { success: false, error: 'Unsupported provider.', code: 'ERR_UNSUPPORTED_PROVIDER' };
      }
    } catch (err) {
      return { success: false, error: err.message, code: 'ERR_AI_GENERATE_FAILED' };
    }
  }

  async traceAndSkeletonize({ imageBase64, traceParams }) {
    try {
      const buffer = Buffer.from(imageBase64, 'base64');
      const jimpImg = await Jimp.read(buffer);

      const params = {
        color: 'white',
        background: 'transparent',
        turnpolicy: traceParams.turnpolicy || potrace.Potrace.TURNPOLICY_MINORITY,
        turdsize: traceParams.turdsize !== undefined ? traceParams.turdsize : 2,
        optcurve: true,
        alphamax: traceParams.alphamax !== undefined ? traceParams.alphamax : 1.0,
        opttolerance: 0.2
      };

      const svg = await new Promise((resolve, reject) => {
        potrace.trace(jimpImg, params, (err, svgOutput) => {
          if (err) reject(err);
          else resolve(svgOutput);
        });
      });

      const widthMatch = svg.match(/width="([^"]+)"/);
      const heightMatch = svg.match(/height="([^"]+)"/);
      const pathMatch = svg.match(/<path[^>]*d="([^"]+)"/i);
      
      if (!widthMatch || !heightMatch || !pathMatch) {
        return { success: false, error: "Failed to parse potrace SVG output.", code: 'ERR_TRACE_PARSING' };
      }

      const origWidth = parseFloat(widthMatch[1]);
      const origHeight = parseFloat(heightMatch[1]);
      const pathData = pathMatch[1];

      const maxDim = Math.max(origWidth, origHeight);
      const scale = 100 / maxDim;
      
      const scaledWidth = origWidth * scale;
      const scaledHeight = origHeight * scale;
      const offsetX = (100 - scaledWidth) / 2;
      const offsetY = (100 - scaledHeight) / 2;

      const finalSvg = `<svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
  <!-- Generated by Astrolabe custom shape wizard -->
  <g transform="translate(${offsetX.toFixed(2)}, ${offsetY.toFixed(2)}) scale(${scale.toFixed(4)})">
    <path d="${pathData}" fill="white" />
  </g>
</svg>`;

      const optimizedSvg = svgo.optimize(finalSvg, {
        multipass: true,
        plugins: [
          {
            name: 'preset-default',
            params: {
              overrides: {
                applyTransforms: true,
                convertPathData: true
              }
            }
          }
        ]
      });

      const skeletonData = await generateSkeletonData(jimpImg);

      return {
        success: true,
        data: {
          svgContent: optimizedSvg.data,
          skeletonData
        }
      };
    } catch (err) {
      return { success: false, error: err.message, code: 'ERR_TRACE_SKELETON_FAILED' };
    }
  }
}

module.exports = ShapeGeneratorService;
