const fs = require('fs');
const path = require('path');
const potrace = require('potrace');

if (process.argv.length < 3) {
  console.error("Usage: node generate-shape.js <input-image-path>");
  process.exit(1);
}

const inputPath = process.argv[2];
const parsedPath = path.parse(inputPath);
const shapeName = parsedPath.name.toLowerCase().replace(/[^a-z0-9_-]/g, '_');

// Output to assets/shapes
const outputDir = path.join(__dirname, '..', 'assets', 'shapes');
const outputPath = path.join(outputDir, `${shapeName}.svg`);

if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

console.log(`Tracing image: ${inputPath}...`);

const PNG = require('pngjs').PNG;
const Jimp = require('jimp');
const { generateSkeletonData } = require('./skeletonizer');

// Configuration for potrace
const params = {
  // SVG output parameters
  color: 'white',
  background: 'transparent',
  // Potrace algorithm parameters
  turnpolicy: potrace.Potrace.TURNPOLICY_MINORITY,
  turdsize: 2,
  optcurve: true,
  alphamax: 1,
  opttolerance: 0.2
};

Jimp.read(inputPath)
  .then((jimpImg) => {
    potrace.trace(jimpImg, params, function(err, svg) {
      if (err) {
        console.error("Failed to trace image:", err);
        process.exit(1);
      }

      const widthMatch = svg.match(/width="([^"]+)"/);
      const heightMatch = svg.match(/height="([^"]+)"/);
      const pathMatch = svg.match(/<path[^>]*d="([^"]+)"/i);
      
      if (!widthMatch || !heightMatch || !pathMatch) {
        console.error("Failed to parse potrace SVG output.");
        process.exit(1);
      }

      const origWidth = parseFloat(widthMatch[1]);
      const origHeight = parseFloat(heightMatch[1]);
      const pathData = pathMatch[1];

      const maxDim = Math.max(origWidth, origHeight);
      const scale = 100 / maxDim;
      
      const scaledWidth = origWidth * scale;
      const scaledHeight = origHeight * scale;
      const offsetX = (100 - scaledWidth) / 2;
      const offsetY = (100 - scaledHeight) / 2;

      const finalSvg = `<svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
  <!-- Generated by Astrolabe generate-shape tool -->
  <g transform="translate(${offsetX.toFixed(2)}, ${offsetY.toFixed(2)}) scale(${scale.toFixed(4)})">
    <path d="${pathData}" fill="white" />
  </g>
</svg>`;

      const svgo = require('svgo');
      const optimizedSvg = svgo.optimize(finalSvg, {
        multipass: true,
        plugins: [
          {
            name: 'preset-default',
            params: {
              overrides: {
                applyTransforms: true,
                convertPathData: true
              }
            }
          }
        ]
      });

      fs.writeFileSync(outputPath, optimizedSvg.data, 'utf8');
      console.log(`✅ Successfully created: ${outputPath}`);
      
      // Generate and save the multi-resolution skeleton graph
      generateSkeletonData(jimpImg).then(skeletonData => {
        const jsonPath = path.join(outputDir, `${shapeName}_skeleton.json`);
        fs.writeFileSync(jsonPath, JSON.stringify(skeletonData), 'utf8');
        console.log(`✅ Successfully created: ${jsonPath}`);
        console.log(`You can now use "${shapeName}" as a custom shape in Astrolabe!`);
      }).catch(err => {
        console.error("Failed to generate skeleton:", err);
      });
    });
  })
  .catch((e) => {
    console.error("Failed to read image:", e.message);
    process.exit(1);
  });
